version: '3'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - DB_HOST=product-db
      - DB_PASSWORD=secret
    depends_on:
      - product-db
    volumes:
      - .:/var/www/html

  product-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: product_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: