apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eshop.fullname" . }}-productservice
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.productservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "eshop.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: productservice
  template:
    metadata:
      labels:
        {{- include "eshop.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: productservice
    spec:
      containers:
        - name: productservice
          image: "{{ .Values.productservice.image.repository }}:{{ .Values.productservice.image.tag }}"
          imagePullPolicy: {{ .Values.productservice.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "eshop.fullname" . }}-productservice-config
          resources:
            {{- toYaml .Values.productservice.resources | nindent 12 }}