apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.fullname" . }}-productservice
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "eshop.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: productservice